export const BookStatus: {
  BUY: 'BUY'
  NOT_STARTED: 'NOT_STARTED'
  IN_PROGRESS: 'IN_PROGRESS'
  COMPLETED: 'COMPLETED'
  GIVEN_UP: 'GIVEN_UP'
} = {
  BUY: 'BUY',
  NOT_STARTED: 'NOT_STARTED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  GIVEN_UP: 'GIVEN_UP',
}
